[package]
name = "{{project}}"
description = "{{}}"
license = "{{license}}"
license_file = "LICENSE"
version = "{{version}}"
edition = "2018"

[lib]
name = "{{project}}"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "^0.14"
features = ["extension-module"]
