version: '3'

services:
  {{project}}-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: {{dockerhub_login}}/{{project}}-cpython:{{version}}
    volumes:
{% for resource in [project, 'Cargo.toml', 'pytest.ini', 'README.md', 'requirements-setup.txt', 'requirements-tests.txt', 'rust-toolchain.toml', 'setup.py', 'src', 'tests'] | sort %}
      - ./{{resource}}:/opt/{{project}}/{{resource}}
{% endfor %}
    entrypoint: pytest
